version: '2'
services:
    crawlerengine-app:
        image: crawler-gateway
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${simlife.registry.password}@crawler-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${simlife.registry.password}@crawler-registry:8761/config
            - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017
            - SPRING_DATA_MONGODB_DATABASE=CrawlerEngine
            - SIMLIFE_SLEEP=30 # gives time for the Simlife Registry to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=crawlerbot/crawlerbot-elasticsearch:9300
        ports:
            - 8081:8081
        external_links:
            - mongo
            - crawlerbot/crawlerbot-elasticsearch
            - crawler-registry
